//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmsChemVS.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compound
    {
        public int Id { get; set; }
        public string compoundName { get; set; }
        public string molecularFormula { get; set; }
        public Nullable<double> molecularWeight { get; set; }
        public Nullable<double> compoundBaseMass { get; set; }
        public string fragmentMsCompound { get; set; }
        public Nullable<int> carbon { get; set; }
        public Nullable<int> hydrogen { get; set; }
        public Nullable<int> nitrogen { get; set; }
        public Nullable<int> oxygen { get; set; }
        public Nullable<int> bromine { get; set; }
        public Nullable<int> iodine { get; set; }
        public Nullable<int> sulfur { get; set; }
        public Nullable<int> phosphorus { get; set; }
        public Nullable<int> chlorine { get; set; }
        public Nullable<int> silicon { get; set; }
        public Nullable<int> flourine { get; set; }
        public string compoundData { get; set; }
    }
}
