//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmsChemVS.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int isotopeId { get; set; }
        public string name { get; set; }
        public Nullable<int> isotopeNumber { get; set; }
        public Nullable<double> atomMass { get; set; }
        public Nullable<double> abundance { get; set; }
    }
}
